# Generated by Django 3.1 on 2020-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convertor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=10)),
                ('c', models.CharField(max_length=10)),
            ],
        ),
    ]
